# This is a basic workflow to help you get started with Actions

name: Destroy Container

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  repo: ${{ github.event.repository.name }}
  env_path: /mnt/env

jobs:
  destroy:
    strategy: 
      matrix:
        os: [lxc-bootstrap]
    runs-on: ${{ matrix.os }}  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      
      - name: terraform init
        run: terraform init

      - name: terraform-destroy
        run: |
          if [ -f "$env_path/$repo/state/terraform.tfstate" ]; then
            terraform destroy -var-file="$env_path/$repo/terraform.tfvars" -state="$env_path/$repo/state/terraform.tfstate" --auto-approve
          else
            echo "State file does not exist"
          fi